# Generated by Django 3.2.16 on 2022-12-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiff',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
